version: '3.8'

services:
  user_management_service:
    build: ./user_management_service
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - DB_NAME=user_management_db
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASSWORD=password

  core_service:
    build: ./core_service
    ports:
      - "8001:8001"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - DB_NAME=core_db
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASSWORD=password

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongodb localhost:27017/test
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mongodb_data: