# Generated by Django 5.1.7 on 2025-04-18 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_customer_supplier_remove_purchase_supplier_id_and_more'),
        ('inventory', '0001_initial'),
        ('product', '0003_remove_color_description_remove_color_hex_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='max_stock_level',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('retail', 'Retail Store'), ('warehouse', 'Warehouse'), ('factory', 'Factory')], default='retail', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'store', 'product_variant')},
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('fabric', 'Fabric'), ('thread', 'Thread'), ('button', 'Button'), ('zipper', 'Zipper'), ('elastic', 'Elastic'), ('trim', 'Trim'), ('lining', 'Lining'), ('interfacing', 'Interfacing'), ('other', 'Other')], max_length=30)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.company')),
            ],
        ),
    ]
