# Generated by Django 5.1.7 on 2025-03-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('inventory', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
        migrations.AddField(
            model_name='payable',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.purchase'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.purchase'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.company'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.currency'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.receivable'),
        ),
        migrations.AddField(
            model_name='report',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.company'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.company'),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.currency'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.paymentmode'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.store'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.sale'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.sale'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.sale'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.subscriptionplan'),
        ),
    ]
