# Generated by Django 5.1.7 on 2025-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='123456(*Udfjio)', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
