# Generated by Django 3.1.12 on 2025-04-29 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('transactions', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payables', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_currency', to='companies.currency')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payables', to='transactions.purchase')),
            ],
            options={
                'db_table': 'payables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_receivables', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_currency', to='companies.currency')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_receivables', to='transactions.sale')),
            ],
            options={
                'db_table': 'receivables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_outs', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_out_currency', to='companies.currency')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_payment_outs', to='financials.payable')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_out_modes', to='transactions.paymentmode')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_outs', to='transactions.purchase')),
            ],
            options={
                'db_table': 'payment_outs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_ins', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_in_currency', to='companies.currency')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_in_modes', to='transactions.paymentmode')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_payment_ins', to='financials.receivable')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payment_ins', to='transactions.sale')),
            ],
            options={
                'db_table': 'payment_ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='companies.company')),
            ],
            options={
                'db_table': 'expense_categories',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_credit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_expenses', to='companies.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_currency', to='companies.currency')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financials.expensecategory')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='transactions.paymentmode')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
