# Generated by Django 3.1.12 on 2025-04-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('financials', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_receivables', to='transactions.sale'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_outs', to='companies.company'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_out_currency', to='companies.currency'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_payment_outs', to='financials.payable'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_out_modes', to='financials.paymentmode'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_outs', to='transactions.purchase'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_ins', to='companies.company'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_in_currency', to='companies.currency'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_in_modes', to='financials.paymentmode'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payment_ins', to='transactions.purchase'),
        ),
        migrations.AddField(
            model_name='paymentin',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payment_ins', to='transactions.sale'),
        ),
        migrations.AddField(
            model_name='payable',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payables', to='companies.company'),
        ),
        migrations.AddField(
            model_name='payable',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_currency', to='companies.currency'),
        ),
        migrations.AddField(
            model_name='payable',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payables', to='transactions.purchase'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_expenses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_currency', to='companies.currency'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financials.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_payments', to='financials.paymentmode'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'name')},
        ),
    ]
